# Generated by Django 4.2.10 on 2024-03-14 14:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default/sneakers.jpg', upload_to=users.models.CustomUser.image_upload_to),
        ),
    ]
